version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'periscope'
      MYSQL_ROOT_HOST: '0.0.0.0'
    ports:
      - "3306:3306"

  mongo-db:
    image: mongo
    ports:
      - "27017:27017"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
#    image: moonbse/backend:latest
    platform: linux/amd64
    depends_on:
      - kafka
      - mysql
      - mongo-db
    ports:
      - "8080:8080"
#    network_mode: bridge

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: moonbse/periscope-frontend:latest
    platform: linux/amd64
    ports:
      - "8085:80"
    depends_on:
      - spring-app
    environment:
      - NODE_ENV=production
